"use client";

import React, { useState } from "react";
import { SideNav } from "@/components/SideNav";
import { CosmicBackground } from "@/components/CosmicBackground";
import { FolderKanban, Plus, Sparkles, Video } from "lucide-react";

interface ProjectItem {
  id: string;
  name: string;
  description: string;
  targetPlatform: "TikTok" | "YouTube Shorts" | "Instagram Reels" | "X / Twitter";
  status: "planning" | "active" | "completed";
  scriptDraft: string;
  createdAt: string;
}

export default function ProjectsPage() {
  const [projectList, setProjectList] = useState<ProjectItem[]>([
    {
      id: "proj-1",
      name: "Siduri AI Venus Avatar Showcase",
      description: "Vertical video demo showcasing Siduri multi-provider LLM switching and animated Venus avatar.",
      targetPlatform: "TikTok",
      status: "active",
      scriptDraft: "Hook: 'What if your AI life assistant looked like a celestial Sumerian sphere?'\nBody: Show stage presenter mode with Venus orbital rings.\nCTA: 'Try Siduri now.'",
      createdAt: "2026-07-21",
    },
    {
      id: "proj-2",
      name: "GLM-4 vs Gemini 2.5 Benchmark Series",
      description: "Comparing Zhipu AI GLM-4 and Google Gemini 2.5 on daily task planning and script generation.",
      targetPlatform: "YouTube Shorts",
      status: "planning",
      scriptDraft: "Script outline being generated by Siduri...",
      createdAt: "2026-07-20",
    },
  ]);

  const [showAddForm, setShowAddForm] = useState(false);
  const [newName, setNewName] = useState("");
  const [newDesc, setNewDesc] = useState("");
  const [newPlatform, setNewPlatform] = useState<ProjectItem["targetPlatform"]>("TikTok");

  const handleAddProject = () => {
    if (!newName.trim()) return;
    const item: ProjectItem = {
      id: `proj-${Date.now()}`,
      name: newName,
      description: newDesc,
      targetPlatform: newPlatform,
      status: "planning",
      scriptDraft: `✦ Script generated by Siduri for ${newName}:\n\nHook: "Attention content creators..."\nBody: "Here is how to automate daily tasks."`,
      createdAt: new Date().toISOString().split("T")[0],
    };

    setProjectList((prev) => [item, ...prev]);
    setNewName("");
    setNewDesc("");
    setShowAddForm(false);
  };

  return (
    <div className="relative flex h-screen w-screen overflow-hidden bg-[#07060a]">
      <SideNav />

      <main className="relative flex-1 overflow-y-auto flex flex-col p-6 md:p-10 text-[#ece4d2]">
        <CosmicBackground parallaxX={0} parallaxY={0} />

        <div className="relative z-10 max-w-6xl w-full mx-auto space-y-10">
          
          {/* Banner Header */}
          <div className="flex flex-wrap items-center justify-between gap-4 border-b border-[#cf9f56]/15 pb-6">
            <div className="flex items-center gap-4">
              <div className="text-[#f0c67e]">
                <FolderKanban className="w-8 h-8 opacity-80" />
              </div>
              <div>
                <h1 className="font-serif text-3xl md:text-4xl text-[#ece4d2] tracking-wide">
                  Content Projects
                </h1>
                <p className="font-mono text-xs text-[#a89f8c] mt-1">
                  Manage vertical video campaigns, short-form scripts, & automated asset generation
                </p>
              </div>
            </div>

            <button
              onClick={() => setShowAddForm(!showAddForm)}
              className="flex items-center gap-2 px-4 py-2 text-[#a89f8c] hover:text-[#f0c67e] transition-colors font-mono text-xs"
            >
              <Plus className="w-4 h-4" />
              <span>New Content Project</span>
            </button>
          </div>

          {/* Add Project Form */}
          {showAddForm && (
            <div className="border border-[#cf9f56]/15 bg-[#0a090e]/40 p-6 space-y-4 animate-fadeIn">
              <h3 className="font-serif text-lg text-[#ece4d2]">Create Content Generation Project</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <input
                  type="text"
                  value={newName}
                  onChange={(e) => setNewName(e.target.value)}
                  placeholder="Project Title (e.g. AI Routine Vlog)..."
                  className="bg-transparent border-b border-[#cf9f56]/20 pb-2 text-[#ece4d2] font-mono text-xs outline-none focus:border-[#f0c67e]/60 transition-colors"
                />
                <select
                  value={newPlatform}
                  onChange={(e) => setNewPlatform(e.target.value as ProjectItem["targetPlatform"])}
                  className="bg-transparent border-b border-[#cf9f56]/20 pb-2 text-[#a89f8c] font-mono text-xs outline-none focus:border-[#f0c67e]/60 transition-colors [&>option]:bg-[#0a090e]"
                >
                  <option value="TikTok">TikTok (9:16 Vertical)</option>
                  <option value="YouTube Shorts">YouTube Shorts (9:16)</option>
                  <option value="Instagram Reels">Instagram Reels</option>
                  <option value="X / Twitter">X / Twitter Thread</option>
                </select>
              </div>
              <textarea
                value={newDesc}
                onChange={(e) => setNewDesc(e.target.value)}
                placeholder="Project description & key message..."
                rows={3}
                className="w-full bg-transparent border-b border-[#cf9f56]/20 pb-2 text-[#ece4d2] font-mono text-xs outline-none focus:border-[#f0c67e]/60 transition-colors mt-4"
              />
              <div className="flex justify-end gap-2 pt-2">
                <button
                  onClick={handleAddProject}
                  className="text-[#f0c67e] hover:text-[#ece4d2] text-xs font-mono transition-colors"
                >
                  Create & Generate Script
                </button>
              </div>
            </div>
          )}

          {/* Project List */}
          <div className="flex flex-col gap-10">
            {projectList.map((proj) => (
              <div key={proj.id} className="group relative flex flex-col gap-4 pb-10 border-b border-[#cf9f56]/10 last:border-0 transition-all">
                <div className="flex items-start justify-between">
                  <div>
                    <div className="flex items-center gap-3 mb-2">
                      <span className="font-mono text-[10px] uppercase tracking-wider text-[#cf9f56]">
                        {proj.targetPlatform}
                      </span>
                      <span className="text-[10px] text-[#5c5749]">•</span>
                      <span
                        className={`text-[10px] font-mono uppercase ${
                          proj.status === "active"
                            ? "text-emerald-400/80"
                            : "text-[#6f8fd6]/80"
                        }`}
                      >
                        {proj.status}
                      </span>
                    </div>

                    <h3 className="font-serif text-2xl text-[#ece4d2] group-hover:text-[#f0c67e] transition-colors">{proj.name}</h3>
                    <p className="text-sm text-[#a89f8c] mt-2 font-sans max-w-3xl leading-relaxed">{proj.description}</p>
                  </div>
                  
                  <a
                    href={`/stage?scene=chat`}
                    className="flex items-center gap-2 text-[#a89f8c] hover:text-[#f0c67e] transition-colors text-xs font-mono"
                  >
                    <Video className="w-4 h-4" />
                    <span>Launch Stage</span>
                  </a>
                </div>

                {/* Script Draft Snippet */}
                <div className="mt-2 pl-4 border-l border-[#cf9f56]/20 space-y-2">
                  <div className="flex items-center gap-2 text-[10px] text-[#cf9f56] uppercase tracking-wider font-mono">
                    <Sparkles className="w-3 h-3" />
                    <span>Siduri Script Draft</span>
                  </div>
                  <pre className="whitespace-pre-wrap font-sans text-sm text-[#8a8373]">
                    {proj.scriptDraft}
                  </pre>
                </div>

                <div className="font-mono text-[10px] text-[#5c5749] uppercase tracking-widest mt-2">
                  Created {proj.createdAt}
                </div>
              </div>
            ))}
          </div>

        </div>
      </main>
    </div>
  );
}
